USE [master]
GO

/****** Object:  Database [TaxisOnTime]    Script Date: 04/19/2011 11:24:43 ******/
CREATE DATABASE [TaxisOnTime] ON  PRIMARY 
( NAME = N'TaxisOnTime', FILENAME = N'L:\Database Development - NEW GROUP\ToT SQL Database\TaxisOnTime.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TaxisOnTime_log', FILENAME = N'L:\Database Development - NEW GROUP\ToT SQL Database\TaxisOnTime_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TaxisOnTime] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TaxisOnTime].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TaxisOnTime] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TaxisOnTime] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TaxisOnTime] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TaxisOnTime] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TaxisOnTime] SET ARITHABORT OFF 
GO

ALTER DATABASE [TaxisOnTime] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [TaxisOnTime] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [TaxisOnTime] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TaxisOnTime] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TaxisOnTime] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TaxisOnTime] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TaxisOnTime] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TaxisOnTime] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TaxisOnTime] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TaxisOnTime] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TaxisOnTime] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TaxisOnTime] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TaxisOnTime] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TaxisOnTime] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TaxisOnTime] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TaxisOnTime] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TaxisOnTime] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TaxisOnTime] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TaxisOnTime] SET  READ_WRITE 
GO

ALTER DATABASE [TaxisOnTime] SET RECOVERY FULL 
GO

ALTER DATABASE [TaxisOnTime] SET  MULTI_USER 
GO

ALTER DATABASE [TaxisOnTime] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TaxisOnTime] SET DB_CHAINING OFF 
GO

